### ISSUE TITLE
announcement on noir

### ISSUE THREAD

**Issue by murtaza52** [fluentforward/cljs-binding#1]
Hi,

This library looks cool, have you announced it on the noir or clojure groups? Also is it avalaible on clojars?

Thanks,
Murtaza

**Comment by mjtodd** [comment]
Hi,
 Glad you like the look of this library. I haven't announced this on the noir or clojure groups yet. It is available on clojars - checkout http://clojars.org/fluentsoftware/cljs-binding. 

Thanks,
 Matt
