### ISSUE TITLE
Uncaught Error: No protocol method ISeqable.-seq defined for type function: function () {cljsbinding.boot()}  

### ISSUE THREAD

**Issue by olivergeorge** [fluentforward/cljs-binding#10]
I'm getting a browser error when using cljs-binding with compiler optimisations turned on.

Uncaught Error: No protocol method ISeqable.-seq defined for type function: function () {cljsbinding.boot()} 

I've setup a simple example here in case you'd like to try and repeat (note: test.cljs needs to go in the src-cljs dir)

https://gist.github.com/3030159

**Comment by mjtodd** [comment]
Hi,
 Thanks for posting that example. Advanced optimisations are not currently supported. I am looking at adding support for this. In the meantime, you should find that setting the optimization level to :simple should work. 

 I am working on supporting advanced optimisations and will let you know when this is done.

**Comment by olivergeorge** [comment]
Thanks.  Will look forward to it.  Might be worth noting so it doesn't surprise anyone.

**Comment by mjtodd** [comment]
Hi. I have now added support for advanced optimization. I will add this to the readme, but a couple of things to be aware of :
1. you need to make sure the cljsbuild settings has externs for jquery e.g.

:cljsbuild {
    :builds [{:source-path "src-cljs"
              :jar true
              :compiler {:output-to "todo.js"
                         :optimizations :advanced
                         :externs ["externs/jquery.js"]
                         :pretty-print true}}]}  
1. Any atoms that you want to bind to need to have export set in the same way any functions you want to export to javascript e.g. 

(def ^:export todos (atom []))

(defn ^:export todocount [](count @todos)
)
