### ISSUE TITLE
Problems with focus on IE8 (& IE7)

### ISSUE THREAD

**Issue by olivergeorge** [fluentforward/cljs-binding#12]
I'm finding that the on change event is stopping focus from changing as expected on IE8 (and IE7).  To change between inputs I have to click or tab twice.

Steps to repeat:
1. Click on first input
2. Enter some text
3. Click or tab to second input

Expected:
Focus cursor should appear in second input

Actual:
Cursor remains in first input until a second click/tab.

**Comment by olivergeorge** [comment]
Here's some sample code for testing...
https://gist.github.com/3038187

**Comment by olivergeorge** [comment]
I think this is resolved by returning nil rather than false from the change event listeners:

https://github.com/olivergeorge/cljs-binding/commit/f23e818418b8dd755f2e0461a020e8e1ebca54f0

**Comment by mjtodd** [comment]
this should now be resolved by changes to click and dbclick handline
