### ISSUE TITLE
support for partials

### ISSUE THREAD

**Issue by murtaza52** [fluentforward/cljs-binding#13]
Hi Matthew, 

Any thoughts on how partials can be added to the library ? This is one functionality that is sorely missing. How do you currently manage it in your projects. cljsone does provide a good starting point. 

Thanks,
Murtaza

**Comment by mjtodd** [comment]
Hi,
 I am currently looking into this as part of a larger task of making it easier to generate bound elements using crate. If you had any examples / thoughts on how you think this would fit for your purposes that would be useful.

Thanks,
 Matthew

**Comment by murtaza52** [comment]
I am basically looking at the different functionality that partials
provide. I started typing this reply by creating examples of my own on what
I wanted, but then realized that I am reproducing

## clojurescriptone's functionality, so I just copied verbatim from their site

To avoid repetition, two new HTML elements are introduced: _include and
_within.

_include will include another HTML file in the current file and
_within indicates
that its content is to be included in another template. When using the
_within tag, HTML ids are used to determine which elements are to be
replaced.

A simple example will show how these new tags may be used.

Suppose we have a layout file templates/layout.html which contains the
following HTML:

<html>
  <head>Example</head>
  <body>
    <_include file="menu.html"/>
    <div id="content"></div>
    <div id="footer"></div>
  </body></html>

Furthermore, suppose we have the following two files named
templates/menu.html and templates/example.html.

<div>Navigation Menu</div>

<_within file="layout.html">
  <div id="content">New Content</div>
  <div id="footer">A Footer</div></_within>

If we point the server at http://localhost:8080/design/example.html, the
following file will be served:

<html>
  <head></head>
  <body>
    <div>Navigation Menu</div>
    <div id="content">New Content</div>
    <div id="footer">A Footer</div>
  </body></html>

Three features are illustrated above -
1) Ability to include another file directly into an existing layout.
(_include)
2) Ability to describe where a component will be included in a layout
(using _within and by specifying ids)
3) Ability to call a component file and have it directly rendered with the
layout.

The 3rd point is a sweet thing to have for RAD. Let me know what you are
planning.

Thanks,
Murtaza

On Tue, Jul 17, 2012 at 2:03 AM, mjtodd <
reply@reply.github.com

**Comment by murtaza52** [comment]
Have you also looked at liftweb, its a scala framework with a very good
templating solution, it also uses plain html templates with custom
attributes.

**Comment by mjtodd** [comment]
Hi,
 Thanks again for your feedback and info on ClojureScript One. I have used lift before and agree, it does have a good templating system.I shall let you know how I am thinking of moving forward with this.

Matthew

**Comment by mjtodd** [comment]
I have recently pushed some changes that make it easier to add bindings dynamically in ClojureScript,as well as added some macros and functions that make it easier to add bindings when using Crate to generate elements. I am considering adding support for enfocus next.
