### ISSUE TITLE
localhost browser (Safari/Firefox) support problems

### ISSUE THREAD

**Issue by rossajmcd** [fluentforward/cljs-binding#14]
Hi.

The todo app running at : http://fluentsoftware.github.com/cljs-binding/todo/index.html is good on all my browsers, but my local cloned copy fails on localhost for Safari and Firefox, latest commit in repo is : '5d2ce08 Matthew Todd: readme update' and I just ran through the instructions in the README to build.

I get the following errors:

TypeError: 'undefined' is not an object (evaluating 'this.s[a]')
SyntaxError: Unexpected token '='

Any ideas ?

Thanks

**Comment by mjtodd** [comment]
Hi,
 I believe I have now fixed this problem with Safari. It is now working on my machine under Safari. 

Please run 'lein deps' to pull down the latest cljs-binding and rebuild the example. 

Thanks,
 Matthew

**Comment by rossajmcd** [comment]
Hi.

I have the same problem after:
- git pull origin master
- lein deps
- lein cljsbuild once

OSX 10.8
Safari Version 6.0 (8536.25).

I ensured the old todo.js was removed, and a new one was built.

Thanks

**Comment by mjtodd** [comment]
Hi, 
 You may find is an issue with cljsbuild files hanging around. If you run

> lein cljsbuild clean
>  lein cljsbuild once

you should find that a clean build works ok in Safari.

Thanks

**Comment by rossajmcd** [comment]
Hi.

Confirmed, now works in all browsers.

Thanks for your help.
