### ISSUE TITLE
binding a textarea

### ISSUE THREAD

**Issue by rossajmcd** [fluentforward/cljs-binding#15]
Hi.

I could not find a mail list for the project, so I'm probably asking a question rather than reporting an issue... is there any reason to think that it is not possible to bind a textarea to an atom ?

Thanks.

**Comment by mjtodd** [comment]
Hi,  
 There should not be any issues with binding a textarea.

Matt

**Comment by bheap** [comment]
Hi.

Can I feature request it for the next release ? :-)

Thanks.

**Comment by mjtodd** [comment]
Hi,
 This is now working correctly, in the same was as with normal text input elements.

Matt

**Comment by rossajmcd** [comment]
Awesome, I'll have a go, thanks!
