### ISSUE TITLE
A single atom for all input fields

### ISSUE THREAD

**Issue by murtaza52** [fluentforward/cljs-binding#2]
Hi,

Is it possible to bind a single atom to all the fields in a form. The atom would be a map and each key in the map will correspond to the respective input id's in the form. 

From the examples I gather that an atom will have to be defined for each input field, rather than one atom for all fields. Is that possible?

Thanks,
Murtaza

**Comment by mjtodd** [comment]
Hi,
 Firstly, sorry for not spotting this issue sooner. It isn't currently possible to bind a single atom to all fields in a form. It is a great idea though, and I will look at implementing this shortly.

Matt

**Comment by mjtodd** [comment]
Hi,
 I have added support for this, updated the readme and also added a maptest example. I have pushed the latest code to clojars, so 1.0.0-SNAPSHOT now contains this addition.

Please do let me know if this change meets your requirements.

Regards,
  Matt

**Comment by murtaza52** [comment]
Hi Matt,

Appreciate your efforts in this regard.

Matt currently we are developing a javascript based application and are
finding it very painful to generate the whole HTML by hand. Your library is
certainly a step in the right direction. However currently I am evaluating
Angular.js and/or derby.js, which makes it trivial to write HTML in a
declarative manner.

Is it possible to evolve your library in this direction? Or maybe leverage
their work by providing a wrapper which generates clojurescript based on
their syntax.

Thanks,
Murtaza

On Wed, Jun 20, 2012 at 2:33 AM, mjtodd <
reply@reply.github.com

**Comment by mjtodd** [comment]
Hi,
 I am looking into ways to either evolve cljs-binding in that direction, or build upon it to provide more facilities for client-side clojurescript / html generation, and synchronisation of state between browser, and server.

If you had any suggestions on what features you would find useful, they would be gratefully received.

Thanks,
 Matt

**Comment by murtaza52** [comment]
To start with there is a crying need to get support for partials and
templates. Maybe the code from clojurescriptone can be leveraged for this.

Thanks,
Murtaza

On Thu, Jun 21, 2012 at 2:04 AM, mjtodd <
reply@reply.github.com

**Comment by murtaza52** [comment]
Matt, however wont it make more sense to create a wrapper for a client side
framework. This way we can leverage all the good work done there.

I am finding derbyjs really cool, and am contemplating on creating a
wrapper around it. Just want to convince myself first that this is the
right thing to do.

**Comment by murtaza52** [comment]
Sorry for the multiple posts !

Ok so here are my thoughts little more organized. There are 3 ways to go
forward -

1) Evolve the current library to provide all the declarative bindings, so
that glue code can be brought o minimum. The features provided by derbyjs
and angular are good examples. This approach will be enlive and enfocus
heavy.

2) Create a wrapper for another framework, such that clojurescript code
written in the library is compiled to js in a format that is compatible
with the other library. Here we are leveraging the powere of the other
framework, while using macros to generate a lot of boiler plate for the
user.

3) Evolve hiccup (crate) to provide all the features as in 1. It is already
competent enough to do the templating, I think only everthing needs to put
together, in a manner that cljsone attempted.

Thanks,
Murtaza

**Comment by mjtodd** [comment]
That's ok. It's great to have some feedback.

I have been looking at using hiccup/crate. I think crate combined with some functions that make the binding easier could be a useful addition to the library.

I'm thinking something along the lines of a function that can be called, passing in an atom that will generate html using crate based on a template function passed in. The generated elements would automatically have all bindings wired up.
