### ISSUE TITLE
Unable to get event binding working

### ISSUE THREAD

**Issue by murtaza52** [fluentforward/cljs-binding#3]
Hi,

I have created a sample project to try out cljsbuild - https://github.com/murtaza52/pm

My index file is https://github.com/murtaza52/pm/blob/master/resources/public/index.html, which has the binding.boot script. 
(I have also added the binding.boot to the onready function through the jayq.ready macro - https://github.com/murtaza52/pm/blob/master/src/pm/client/main.cljs)

The following file - https://github.com/murtaza52/pm/blob/master/resources/public/templates/components.html - contains a click event for the link with id "add-new-project".

The click event - (hello) - is defined in this file - https://github.com/murtaza52/pm/blob/master/src/pm/client/templating.cljs 

The page displays without any error, however nothing happens on the click of Projects -> Add . 

I am also not manually able to call cljsbinding.boot from the browsers console. 

I will appreciate if you can point out that what is wrong ?

Thanks,
Murtaza

The

**Comment by murtaza52** [comment]
Please look at the cljs-binding branch for the above code.

**Comment by mjtodd** [comment]
I have had a look at your project. One point is that cljsbinding.boot is being called before the client-side DOM manipulation has completed, so it will not see your elements with the bind attribute.

There are two ways around this. One is to call cljsbinding.boot later. Another option, which may be preferable if you are manipulating the DOM dynamically is to call cljsbinding.bindall(elem) e.g. cljsbinding.bindall(jayq.core.$('#header'))

I have tried this on your project, but for some reason see the error " Error: No protocol method ISeqable.-seq defined for type object: [object Object]" when calling bindall. I am trying to work out what is causing this at the moment

**Comment by mjtodd** [comment]
It looks like this is something to do with jayq implementing ISeqable - cljs.core.seq.call(null,jayq.core.$('#header')) produces the same error. I will try to work out what could be causing that as this works on other test projects I have.

**Comment by mjtodd** [comment]
Hi,
 I have managed to resolve the errors with the project.
1. The first issue as I mentioned before is that cljsbinding.boot was being called before the elements were added to the DOM. This can be resolved by calling cljsbinding.bindall($('#header')), or by calling boot later
2. You had a <script> tag that was pulling in jQuery. This is not needed as jayq does this for you. By importing jQuery again it was effectively removing some the the jQuery extensions that jayq had added, causing the ISeqable issue.
3. The hello function you were setting up in your click handler was missing.

I also noticed you were using a more recent version of jayq than I was - 0.1.0-alpha4, so I have updated cljs-binding to use this newer version.

 A diff of the changes I made is below. Note. I was just manually calling cljsbinding.bindall($('#header')) from the js console to setup the binding.

diff --git a/resources/public/templates/components.html b/resources/public/templ
index 2f6e120..a7f83ae 100644
--- a/resources/public/templates/components.html
+++ b/resources/public/templates/components.html
@@ -87,6 +87,5 @@
         </div>
       </div>
     </div>  
-    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.j
  </body>
  </html>
  diff --git a/src/pm/client/templating.cljs b/src/pm/client/templating.cljs
  index 41531ab..f9d1457 100644
  --- a/src/pm/client/templating.cljs
  +++ b/src/pm/client/templating.cljs
  @@ -41,5 +41,7 @@
  (let [c (project-page)](layout c)))

+(defn hello [] #(js/alert "Hello"))
+
 (comment
 )

I hope this helps. Any other questions, feel free to reopen this issue, or add new issues.

Kind Regards and thanks again for the feedback,

 Matthew

**Comment by murtaza52** [comment]
Thanks Matthew. Really appreciate your help.

1) Matthew I am also pulling in jquery in my index.html page, and that
doesnt seem to overwrite jayq's extensions, why so ?

2) If you look at noir-cljs, from Chris Granger, in that he provides a
defpartial "include-scripts" which actually includes jquery explicitly
along with the compiled cljs.

(defpartial include-scripts [& [jquery?]](when jquery?
    %28include-js))
  (include-js "/cljs/bootstrap.js"))

So I believe its the order that is creating the problems, if the jquery is
included before the index, cljs then it doesn't overwrite.

In my case I had a snippet file in which the jquery was included long back
only for testing purpose, and then I forgot to remove it. So when this file
was loaded from the system, it also retrieved the jquery and inadvertently
overwrote the extensions ! Wow !

Thanks,
Murtaza

On Thu, Jun 28, 2012 at 2:20 AM, mjtodd <
reply@reply.github.com
