### ISSUE TITLE
Typo in dependencies copy

### ISSUE THREAD

**Issue by olivergeorge** [fluentforward/cljs-binding#4]
This is what is in your README under usage (note "." before SNAP)
                 [fluentsoftware/cljs-binding "1.0.0-SNAPSHOT"]]

This is what clojars requires...  (note the "-" before SNAP)
                 [fluentsoftware/cljs-binding "1.0.0-SNAPSHOT"]]

**Comment by mjtodd** [comment]
Thanks for spotting this. I've corrected it now.
