### ISSUE TITLE
Initializing DOM bindings

### ISSUE THREAD

**Issue by murtaza52** [fluentforward/cljs-binding#5]
Hi,

In my application I will be loading different HTML snippets. Each of this snippet will have a binding defined to an atom. How do I initialize the binding ONLY on the new DOM elements when they are loaded ? 

Below is the map to which I will be binding -

``` clojure
(ns pm.client.models)

(def new-project (atom {:hello 2}))
```

Below is the snippet that I have added to the DOM on which I want to initialize the bindings 

``` HTML
<div class="control-group">
                <label class="control-label" for="input01">Project Name</label>
                <div class="controls">
                  <input type="text" class="input-xlarge"
                         id="name" bindatom="pm.client.models.new-project"/>
                </div>
              </div>
              <div class="control-group">
                <label class="control-label" for="textarea">Project Description</label>
                <div class="controls">
                  <textarea class="input-xlarge" id="project-desc"
                            rows="3"  id="desc" bindatom="pm.client.models.new-project"></textarea>
                </div>
              </div>
```

Thanks,
Murtaza

**Comment by mjtodd** [comment]
Hi Murtaza,
 To bind to new elements, you can call the cljsbinding.bindall function passing in the element e.g. (binding/bindall ($ ".control-group"))  . This will setup all bindings for the element passed in, and all descendants of that element.

Does this provide what you were looking for?

**Comment by murtaza52** [comment]
Yup it does. However is there a generic call that I can make like
cljsbind.boot ?

On Fri, Jun 29, 2012 at 1:35 AM, mjtodd <
reply@reply.github.com

**Comment by murtaza52** [comment]
binding/bindall takes two arguments, what is the purpose of the second one?

**Comment by mjtodd** [comment]
the second argument is a context, which is used by bindseq to bind to each item in the sequence. bindseq will call bindall passing in the item from the sequence it is binding as the context.

**Comment by mjtodd** [comment]
the context argument to bindall is now optional (also fixes one of the warnings you mentioned in the other issue)
