### ISSUE TITLE
unable to bind a function call to a button

### ISSUE THREAD

**Issue by murtaza52** [fluentforward/cljs-binding#7]
Hi,

I have created a simple button - 

``` html
 <button id="cljsbutton" class="btn" bind="click: pm.client.templating.hello" >Cljs Click Event</button>
```

https://github.com/murtaza52/pm/blob/master/resources/public/index.html

When I load the page, the hello function gets called ( js alert) even without the click. And on clicking the button nothing happens

I see the same behavior when I try to manually bind it after the page is loaded. When I type the following command on the console - cljsbinding.bindall($("#cljsbutton")); - I see the hello funciton is called, however on subsequently clicking on the button nothing happens.

Thanks,
Murtaza

**Comment by mjtodd** [comment]
Hi, 
 The jquery click method on an element expects a function to be passed to it, so the function that you pass in, in your case pm.client.templating.hello should return a function e.g.

(defn hello [] #(js/alert "Hello"))

if your click handler was inside a bindseq, then your function would take a single parameter which would be the item from within the sequence e.g. from the todo example:

(defn ^:export click-toggle [item]
  #(toggle item)
)

**Comment by murtaza52** [comment]
Matthew,

That explains it thanks. However shouldn't the (defn hello [] #(js/alert
"Hello")) function be passed itself as a function instead of its return
value ?

This means a wrapper function will need to be created for every click
handler, so that it returns its contents as a function ?

Thanks,
Murtaza

On Fri, Jun 29, 2012 at 12:27 PM, mjtodd <
reply@reply.github.com

**Comment by mjtodd** [comment]
Hi Murtaza,
 I have updated 1.0.0-SNAPSHOT with a fix for this so that for click, and dblclick, the wrapper function is no longer required.

Matthew

**Comment by murtaza52** [comment]
Hi Matthew,

That is great, I will update my code to reflect it.

Thanks,
Murtaza

On Mon, Jul 2, 2012 at 1:31 AM, mjtodd <
reply@reply.github.com
